name: 'lion-prod'

services:
  
  frontend:
    build:
      context: ../../ 
      dockerfile: ./infrastructure/prod/frontend.Dockerfile
    depends_on:
      - backend
    networks:
      - frontend_to_backend
    ports: 
      - 4200:80
  
  backend:
    build: 
      context: ../../
      dockerfile: ./infrastructure/prod/backend.Dockerfile
    depends_on:
      - mongo
    networks:
      - frontend_to_backend
      - backend_to_mongo
      - backend_to_graphdb
  
  mongo:
    image: mongo
    restart: always
    volumes:
      - type: volume
        source: mongo
        target: /data/db
    networks:
      - mongo-express_to_mongo
      - backend_to_mongo
  
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    networks:
      - mongo-express_to_mongo

  graphdb:
    image: ontotext/graphdb:10.5.1
    # todo: remove port forwarding to host, in production only the backend should access the graphdb
    ports: 
      - 7200:7200
    volumes:
      - type: volume
        source: graphdb
        target: /opt/graphdb/home/data
    networks:
      - backend_to_graphdb

volumes:
  mongo:
  graphdb:

networks:
  frontend_to_backend:
  backend_to_mongo:
  mongo-express_to_mongo:
  backend_to_graphdb:
