name: 'lion-dev'
version: '3.8'

services:

  # graphdb for ontology data
  graphdb:
    image: ontotext/graphdb:10.5.1
    ports: 
      - 7200:7200
    volumes:
      - type: volume
        source: graphdb
        target: /opt/graphdb/home/data

  # mysql for eclass
  mysql:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
    ports:
      - 3306:3306

  # admin webapp for mysql
  adminer:
    image: adminer:4.8.1
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080

  # mogo db for user mgmt
  mongo:
    image: mongo:7.0.5
    restart: always
    volumes:
      - type: volume
        source: mongo
        target: /data/db
    ports: 
      - 27017:27017

  # admin webapp for mongodb
  mongo-express:
    image: mongo-express:1.0.2
    restart: always
    ports:
      - 8081:8081

volumes:
  graphdb:
  mongo:
  mysql: